### PR TITLE
Add minimp3

### PR DESCRIPTION
**Pull request by lieff**
ISO conformant mini MP3 decoder with sse/neon support.

### CODE REVIEW

**Comment by kozross** [comment]
I always like more microlibraries, but this raises a few questions from me. Firstly, there's no documentation; secondly, despite its claim that it's 'ISO conformant', it also has this:

    Conformance test fails on all vectors (PSNR < 96db), free format is not supported.

Which suggests it _isn't_ conformant. Would you be able to clear that up?

**Comment by lieff** [comment]
Keyj http://keyj.emphy.de/minimp3/ isn't conformant. This is the reason I create new one, primarily for https://github.com/lieff/lvg . I've plan to add some documentation, but I need someone with native English  to create one.

**Comment by kozross** [comment]
@lieff Thanks for the clarification. As I am not an expert on MP3 or audio, I don't feel comfortable merging this without docs. Once they are added, however, I would be happy to reconsider. I will keep this PR open in the meantime.

**Comment by lieff** [comment]
I've add some simple usage doc in readme.

**Comment by lieff** [comment]
More enhanced doc added.

**Comment by kozross** [comment]
@lieff That looks better. I'll make a PR to correct the spelling, punctuation, grammar and style some time today. Please rebase your commit on the latest master after this happens, and I'll merge happily.

**Comment by lieff** [comment]
Rebased)

**Comment by kozross** [comment]
Thank you for your contribution!

**Pull request merged**
