### PR TITLE
Added ONLY_ONCE

### PR DESCRIPTION
**Pull request by hexspeakerg**

### CODE REVIEW

**Comment by kozross** [comment]
Thanks for your contribution - this is really cool!

**Comment by bizulk** [comment]
I've read the macro, it is just a check and set on a static variable, there is no atomicity on theses two operation and therefore no garantee that the code is executed only once beetween threads.

Moreover the code évaluate the affectation I doubt that this is an efficient code.
When a variable is set in different contect, we declare it as volatile so that the compiler does not cache it's value.

If we want some synchronization one should use some mutex, or C11 [__atomic built-in functions](https://stackoverflow.com/questions/25319825/how-to-use-atomic-variables-in-c), even write his own non interruptible function according to the CPU possibilities (like those ARM ASM instructions LDREX/STREX), or even lock thread scheduling.

Don't use that stuff, or just write it clearly that it is not thread safe.

**Comment by hexamage** [comment]
@bizulk 

I did add a version that uses `thread_local` storage, but that is a different thing. I completely forgot to add volatile so that the compiler does not optimize the value. I will update that immediately.

I did not find any errors when testing multiple threads, though. **Could you show me some code that causes it to fail?**

I guess I could just make the variable `_Atomic` to fix the synchronization issues, although that would make the operation a bit more expensive, but it makes sense if it's needed for proper execution.

**Comment by bizulk** [comment]
OK. I'll put an eye on it.
About the _Atomic variable I don't know much about it.
I've read/used many check and set that way on the past, that results with computing errors in particular cases.

Analysing the resulting assembly code is relevant : the lock is not an atomic operation, 

- LDR R0 [value]
- CMP R0 0
- STRN 1 [value]

If preempted between the second step and the third by a thread with higher priority, that one will see the value = 0, set it to 1, execute the code, and when the scheduler passes back to the first thread, this one will not see the check and also execute code.
In some cases such lock has no consequence, but for that particular case it is not sufficient.

**Pull request merged**
