### PR TITLE
add a tutorial for autotools which show how to build portable C program

### PR DESCRIPTION
**Pull request by stevenleeS0ht**
Autotools is a awesome tools to build portable C program. This tutorial provide a complete introduction toward this tool. It is very helpful to beginner. But there are some difficult part, so I put it in intermediate material list.

### CODE REVIEW

**Comment by stevenleeS0ht** [comment]
libgit2 is also a powerful tool, which Julia PackageManager is based on it.

**Comment by Bfgeshka** [comment]
Probably should separate it into different PR.

**Comment by stevenleeS0ht** [comment]
@Bfgeshka , Yes, but how can I put it in a different PR? when I click "New Request", it will automatically append it on its tail.

**Comment by Bfgeshka** [comment]
Dunno, but I'd suggest to PR from different branch, it should do the trick.

**Comment by kozross** [comment]
I will address the tutorial pull separately - if you would like to contribute libgit2 as well, please make a separate PR after this one has been dealt with. I don't consider the Autotools as something that belongs on this list, for reasons similar to [these][1]. As a result, I don't (or rather, _shouldn't_) list anything Autotools-related here. If you can make a convincing argument about why _modern_ C should be making use of the Autotools over CMake or Meson, I would be willing to re-introduce the Autotools (along with this tutorial).

[1]: http://voices.canonical.com/jussi.pakkanen/2011/09/13/autotools/

**Comment by stevenleeS0ht** [comment]
@kozross , C is a native language, it is different from Python or Java. As a result, the portability of program become a big issue to the user of C.  In addition, C projects usually contains thousands of source files. it would be a challenge to write Makefile with bare hand. However, meta-build tools like autotools could effectively solve the issues above. As a result, the meta-build tools could be the best friend to the  C user. Since, every reader of this list is C user, even though meta-build tools itself is not a standard part of C language, the majority of reader will obtain a lot of benefit if they learn some thing about this tools. Furthermore, due to the authority of GNU projects. Autotools almost become a standard tools in Open Source C world. Overall, I strongly recommend you to add them in the list.

**Comment by kozross** [comment]
@stevenleeS0ht I am aware of all the above. Are you familiar with CMake or Meson? They solve all the problems you describe, and avoid all the problems of described in my link.

**Comment by stevenleeS0ht** [comment]
@kozross , Could you please close this PR? I am unable to add a new PR.

**Pull request closed without merging**
