### PR TITLE
add libgit2

### PR DESCRIPTION
**Pull request by stevenleeS0ht**
add libgit2 in **Source Code Management**

### CODE REVIEW

**Comment by stevenleeS0ht** [comment]
I have already resolve the conflict by changing link number. If it still conflict, please help me to correct it. Because, when I correct, you may no notice it immediately, as a result, there will be add some new stuff in it. Then the new link number might still be conflict.

**Comment by kozross** [comment]
@stevenleeS0ht Thanks for doing that! However, it's still missing a license link, as required according to the CONTRIBUTING file.

**Comment by stevenleeS0ht** [comment]
Then, could you please provide me a merge-conflict link, in order to make it easier to edit online.

**Comment by stevenleeS0ht** [comment]
If it is easier, please help me to add gplv2 in libgit2, the reference is [here](https://github.com/libgit2/libgit2/blob/master/COPYING)

**Comment by kozross** [comment]
Sorry for the delay, merged it myself. Thank you for your contribution!

**Pull request closed without merging**
