### PR TITLE
Add rb3ptr (Red-Black tree).

### PR DESCRIPTION
**Pull request by jstimpfle**

### CODE REVIEW

**Comment by kozross** [comment]
Is this included in [this library by the same author][1]? If so, I think it's better to include that library, as it covers more ground, has much more documentation, and is easier to report bugs to.

[1]: https://github.com/jstimpfle/sil

**Comment by jstimpfle** [comment]
That's where I started rb3ptr, but I'm probably going to remove that repository. The other stuff is mostly a bad benchmarking setup, an AVL implementation that has a bug I've never fixed, and another, 2-pointer Red-black tree (that I've never used productively - and 2-pointers are less useful in general).

**Comment by kozross** [comment]
Oh, I had no idea that was your work! Do you have a repo with _just_ the red-black tree implementation then?

**Comment by jstimpfle** [comment]
It is located under my github handle, so yeah it's me :-)

I prefer to leave the external webpage (as in the pull request) as the project's home. But to provide for possibly simpler collaboration, I've just created a github repository that has just the rb3ptr code, and I've linked it from the webpage. What do you think?

**Comment by kozross** [comment]
Sorry this took a while - that makes sense. My only complaint is that an example of use in the README on the repo would be really helpful. If you can add that, I'll happily merge.

**Comment by jstimpfle** [comment]
I've added some example code to the github repo.

**Comment by kozross** [comment]
Thank you for your contribution!

**Pull request merged**
